### ISSUE TITLE
GitHub commit checks have started to fail without discernible reason

### ISSUE THREAD

**Issue by torfason** [rticulate/import#60]
The commit checks triggered by pull requests such as #55 currently fail even though they passed at the time of the last release, and nothing seems to have changed in the package that should cause such the failure. See for example the results here:

https://github.com/rticulate/import/runs/5777825787?check_suite_focus=true

This is kind of a blocker for a new release of `import`, but I'm personally not too proficient with GitHub actions, so I would very much appreciate assistance with this.

**Comment by brshallo** [comment]
Am guessing you have a problem in [.github/workflows/pkgdown.yaml](https://github.com/rticulate/import/blob/master/.github/workflows/pkgdown.yaml). I compared import's setup to my set-up of pkgdown on a recent package I wrote that is working (see file at [brshallo/funspotr/.../pkgdown.yaml](https://github.com/brshallo/funspotr/blob/main/.github/workflows/pkgdown.yaml)) and noticed a few subtle differences. 

One is that I'm using the `v1` rather than the `master` branch for setting-up pandoc.

imports does: 
```yaml
      - uses: r-lib/actions/setup-pandoc@master
```

funspotr does:

```
      - uses: r-lib/actions/setup-pandoc@v1
```

I checked a more established package and it seems like [dplyr/.../pkgdown.yaml](https://github.com/tidyverse/dplyr/blob/main/.github/workflows/pkgdown.yaml) also uses `v1`.

**Comment by torfason** [comment]
Thanks for the pointers, it turned out to be a bit more than the pandoc version, but comparing to other repos and updating to the current examples in r-lib/actions took care of this. :-)

**Comment by torfason** [comment]
This now works as intended, all checks are passing on `master` and `dev`
